spring:
 # profiles:
  #  active: production
  logging:
    level:
        org.springframework.web: DEBUG
   
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #  Let built-in Eureka Client not to register with ‘itself’, because our application should be acting as a server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka:123456789@localhost:8761/eureka/
      
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: 123456789