spring:
  profiles:
    active: production

  security:
    # Credentials for login via UI
    user:
      name: eureka
      password: 123456789

server:
    port: 8761
eureka:
  #  Let built-in Eureka Client not to register with ‘itself’, because our application should be acting as a server
  client:
    registerWithEureka: false
    fetchRegistry: false